name: Step Types

on:
    workflow_dispatch:

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-22.04
        steps:
            - run: |
                    echo "Hello from an inline bash script in a Github Action"
    
    say-hello-inline-python:
        runs-on: ubuntu-22.04
        steps:
            - run: print("Hello from inside inline python script")
              shell: python # We can mention the shell here
    
    say-hello-action:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/hello-world-javascript-action@081a6d193d1dcb38460df1e6927486d748730f9d
              with:
                who-to-greet: "from an action in the Github Action Marketplace!"